package odoo

import (
	"fmt"
	"time"
)

// Added this method to a file called `custom_product` as our files are autogenerated this will stop any
// custom queries being removed.

// GetAllProducts gets all product.product records that have been created within the time passed in.
// This allows us to run a cron job every x minutes and find new products. We return encoded JSON within this method
// which makes it easy to use within XFuze.
func (c *Client) GetAllProducts(productsFrom time.Time) ([]byte, error) {
	criteria := NewCriteria()
	dtLayout := "2006-01-02 15:04:05"
	fmt.Printf("Looking for products created after %s", productsFrom.Format(dtLayout))
	criteria.Add("create_date", ">=", productsFrom.Format(dtLayout))

	return c.SearchReadJSON(ProductProductModel, criteria, NewOptions())
}
