package odoo

import (
	"log"
	"time"
)

// Added this method to a file called `custom_product` as our files are autogenerated this will stop any
// custom queries being removed.

// GetProductsCreatedAfter gets all product.product records that have been created after the time passed in.
// This allows us to run a cron job every x minutes and return new products. We return encoded JSON
// within this method which makes it easy to use within XFuze.
func (c *Client) GetProductsCreatedAfter(t time.Time) ([]byte, error) {
	criteria := NewCriteria()
	dtLayout := "2006-01-02 15:04:05"
	log.Printf("Looking for products created after %s", t.Format(dtLayout))
	criteria.Add("create_date", ">=", t.Format(dtLayout))

	return c.SearchReadJSON(ProductProductModel, criteria, NewOptions())
}
