version: 2
tasks:
  test:
    desc: runs all tests
    cmds:
      - go test -v -cover -race ./...

  int-tests:
    desc: runs the int tests
    cmds:
      - go test -v -race -tags=integration ./...

  lint:
    desc: run the linter on the code
    cmds:
      - command -v golangci-lint > /dev/null || GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - golangci-lint run