package types

import (
	"time"
)

type ResConfigSettings struct {
	AccountHideSetupBar                  bool      `xmlrpc:"account_hide_setup_bar"`
	AliasDomain                          string    `xmlrpc:"alias_domain"`
	AuthSignupResetPassword              bool      `xmlrpc:"auth_signup_reset_password"`
	AuthSignupTemplateUserId             Many2One  `xmlrpc:"auth_signup_template_user_id"`
	AuthSignupUninvited                  string    `xmlrpc:"auth_signup_uninvited"`
	AutoDoneSetting                      bool      `xmlrpc:"auto_done_setting"`
	ChartTemplateId                      Many2One  `xmlrpc:"chart_template_id"`
	CodeDigits                           int64     `xmlrpc:"code_digits"`
	CompanyCurrencyId                    Many2One  `xmlrpc:"company_currency_id"`
	CompanyId                            Many2One  `xmlrpc:"company_id"`
	CompanySharePartner                  bool      `xmlrpc:"company_share_partner"`
	CompanyShareProduct                  bool      `xmlrpc:"company_share_product"`
	CreateDate                           time.Time `xmlrpc:"create_date"`
	CreateUid                            Many2One  `xmlrpc:"create_uid"`
	CrmAliasPrefix                       string    `xmlrpc:"crm_alias_prefix"`
	CurrencyExchangeJournalId            Many2One  `xmlrpc:"currency_exchange_journal_id"`
	CurrencyId                           Many2One  `xmlrpc:"currency_id"`
	DefaultCustomReportFooter            bool      `xmlrpc:"default_custom_report_footer"`
	DefaultDepositProductId              Many2One  `xmlrpc:"default_deposit_product_id"`
	DefaultExternalEmailServer           bool      `xmlrpc:"default_external_email_server"`
	DefaultInvoicePolicy                 string    `xmlrpc:"default_invoice_policy"`
	DefaultPickingPolicy                 string    `xmlrpc:"default_picking_policy"`
	DefaultPurchaseMethod                string    `xmlrpc:"default_purchase_method"`
	DefaultPurchaseTaxId                 Many2One  `xmlrpc:"default_purchase_tax_id"`
	DefaultSaleTaxId                     Many2One  `xmlrpc:"default_sale_tax_id"`
	DefaultUserRights                    bool      `xmlrpc:"default_user_rights"`
	DisplayName                          string    `xmlrpc:"display_name"`
	ExternalReportLayout                 string    `xmlrpc:"external_report_layout"`
	FailCounter                          int64     `xmlrpc:"fail_counter"`
	GenerateLeadFromAlias                bool      `xmlrpc:"generate_lead_from_alias"`
	GroupAnalyticAccountForPurchases     bool      `xmlrpc:"group_analytic_account_for_purchases"`
	GroupAnalyticAccounting              bool      `xmlrpc:"group_analytic_accounting"`
	GroupCashRounding                    bool      `xmlrpc:"group_cash_rounding"`
	GroupDiscountPerSoLine               bool      `xmlrpc:"group_discount_per_so_line"`
	GroupDisplayIncoterm                 bool      `xmlrpc:"group_display_incoterm"`
	GroupManageVendorPrice               bool      `xmlrpc:"group_manage_vendor_price"`
	GroupMassMailingCampaign             bool      `xmlrpc:"group_mass_mailing_campaign"`
	GroupMultiCompany                    bool      `xmlrpc:"group_multi_company"`
	GroupMultiCurrency                   bool      `xmlrpc:"group_multi_currency"`
	GroupPricelistItem                   bool      `xmlrpc:"group_pricelist_item"`
	GroupProductPricelist                bool      `xmlrpc:"group_product_pricelist"`
	GroupProductVariant                  bool      `xmlrpc:"group_product_variant"`
	GroupProformaSales                   bool      `xmlrpc:"group_proforma_sales"`
	GroupRouteSoLines                    bool      `xmlrpc:"group_route_so_lines"`
	GroupSaleDeliveryAddress             bool      `xmlrpc:"group_sale_delivery_address"`
	GroupSaleLayout                      bool      `xmlrpc:"group_sale_layout"`
	GroupSalePricelist                   bool      `xmlrpc:"group_sale_pricelist"`
	GroupShowPriceSubtotal               bool      `xmlrpc:"group_show_price_subtotal"`
	GroupShowPriceTotal                  bool      `xmlrpc:"group_show_price_total"`
	GroupStockAdvLocation                bool      `xmlrpc:"group_stock_adv_location"`
	GroupStockMultiLocations             bool      `xmlrpc:"group_stock_multi_locations"`
	GroupStockMultiWarehouses            bool      `xmlrpc:"group_stock_multi_warehouses"`
	GroupStockPackaging                  bool      `xmlrpc:"group_stock_packaging"`
	GroupStockProductionLot              bool      `xmlrpc:"group_stock_production_lot"`
	GroupStockTrackingLot                bool      `xmlrpc:"group_stock_tracking_lot"`
	GroupStockTrackingOwner              bool      `xmlrpc:"group_stock_tracking_owner"`
	GroupSubtaskProject                  bool      `xmlrpc:"group_subtask_project"`
	GroupUom                             bool      `xmlrpc:"group_uom"`
	GroupUseLead                         bool      `xmlrpc:"group_use_lead"`
	GroupWarningAccount                  bool      `xmlrpc:"group_warning_account"`
	GroupWarningPurchase                 bool      `xmlrpc:"group_warning_purchase"`
	GroupWarningSale                     bool      `xmlrpc:"group_warning_sale"`
	GroupWarningStock                    bool      `xmlrpc:"group_warning_stock"`
	HasAccountingEntries                 bool      `xmlrpc:"has_accounting_entries"`
	HasChartOfAccounts                   bool      `xmlrpc:"has_chart_of_accounts"`
	Id                                   int64     `xmlrpc:"id"`
	IsInstalledSale                      bool      `xmlrpc:"is_installed_sale"`
	LastUpdate                           time.Time `xmlrpc:"__last_update"`
	LeaveTimesheetProjectId              Many2One  `xmlrpc:"leave_timesheet_project_id"`
	LeaveTimesheetTaskId                 Many2One  `xmlrpc:"leave_timesheet_task_id"`
	LockConfirmedPo                      bool      `xmlrpc:"lock_confirmed_po"`
	ModuleAccount3wayMatch               bool      `xmlrpc:"module_account_3way_match"`
	ModuleAccountAccountant              bool      `xmlrpc:"module_account_accountant"`
	ModuleAccountAsset                   bool      `xmlrpc:"module_account_asset"`
	ModuleAccountBankStatementImportCamt bool      `xmlrpc:"module_account_bank_statement_import_camt"`
	ModuleAccountBankStatementImportCsv  bool      `xmlrpc:"module_account_bank_statement_import_csv"`
	ModuleAccountBankStatementImportOfx  bool      `xmlrpc:"module_account_bank_statement_import_ofx"`
	ModuleAccountBankStatementImportQif  bool      `xmlrpc:"module_account_bank_statement_import_qif"`
	ModuleAccountBatchDeposit            bool      `xmlrpc:"module_account_batch_deposit"`
	ModuleAccountBudget                  bool      `xmlrpc:"module_account_budget"`
	ModuleAccountDeferredRevenue         bool      `xmlrpc:"module_account_deferred_revenue"`
	ModuleAccountPayment                 bool      `xmlrpc:"module_account_payment"`
	ModuleAccountPlaid                   bool      `xmlrpc:"module_account_plaid"`
	ModuleAccountReports                 bool      `xmlrpc:"module_account_reports"`
	ModuleAccountReportsFollowup         bool      `xmlrpc:"module_account_reports_followup"`
	ModuleAccountSepa                    bool      `xmlrpc:"module_account_sepa"`
	ModuleAccountSepaDirectDebit         bool      `xmlrpc:"module_account_sepa_direct_debit"`
	ModuleAccountTaxcloud                bool      `xmlrpc:"module_account_taxcloud"`
	ModuleAccountYodlee                  bool      `xmlrpc:"module_account_yodlee"`
	ModuleAuthLdap                       bool      `xmlrpc:"module_auth_ldap"`
	ModuleAuthOauth                      bool      `xmlrpc:"module_auth_oauth"`
	ModuleBaseGengo                      bool      `xmlrpc:"module_base_gengo"`
	ModuleBaseImport                     bool      `xmlrpc:"module_base_import"`
	ModuleCrmPhoneValidation             bool      `xmlrpc:"module_crm_phone_validation"`
	ModuleCurrencyRateLive               bool      `xmlrpc:"module_currency_rate_live"`
	ModuleDelivery                       bool      `xmlrpc:"module_delivery"`
	ModuleDeliveryBpost                  bool      `xmlrpc:"module_delivery_bpost"`
	ModuleDeliveryDhl                    bool      `xmlrpc:"module_delivery_dhl"`
	ModuleDeliveryFedex                  bool      `xmlrpc:"module_delivery_fedex"`
	ModuleDeliveryUps                    bool      `xmlrpc:"module_delivery_ups"`
	ModuleDeliveryUsps                   bool      `xmlrpc:"module_delivery_usps"`
	ModuleGoogleCalendar                 bool      `xmlrpc:"module_google_calendar"`
	ModuleGoogleDrive                    bool      `xmlrpc:"module_google_drive"`
	ModuleGoogleSpreadsheet              bool      `xmlrpc:"module_google_spreadsheet"`
	ModuleHrOrgChart                     bool      `xmlrpc:"module_hr_org_chart"`
	ModuleHrTimesheet                    bool      `xmlrpc:"module_hr_timesheet"`
	ModuleInterCompanyRules              bool      `xmlrpc:"module_inter_company_rules"`
	ModuleL10nEuService                  bool      `xmlrpc:"module_l10n_eu_service"`
	ModuleL10nUsCheckPrinting            bool      `xmlrpc:"module_l10n_us_check_printing"`
	ModulePad                            bool      `xmlrpc:"module_pad"`
	ModulePrintDocsaway                  bool      `xmlrpc:"module_print_docsaway"`
	ModuleProcurementJit                 string    `xmlrpc:"module_procurement_jit"`
	ModuleProductEmailTemplate           bool      `xmlrpc:"module_product_email_template"`
	ModuleProductExpiry                  bool      `xmlrpc:"module_product_expiry"`
	ModuleProductMargin                  bool      `xmlrpc:"module_product_margin"`
	ModuleProjectForecast                bool      `xmlrpc:"module_project_forecast"`
	ModuleProjectTimesheetHolidays       bool      `xmlrpc:"module_project_timesheet_holidays"`
	ModuleProjectTimesheetSynchro        bool      `xmlrpc:"module_project_timesheet_synchro"`
	ModulePurchaseRequisition            bool      `xmlrpc:"module_purchase_requisition"`
	ModuleRatingProject                  bool      `xmlrpc:"module_rating_project"`
	ModuleSaleCoupon                     bool      `xmlrpc:"module_sale_coupon"`
	ModuleSaleMargin                     bool      `xmlrpc:"module_sale_margin"`
	ModuleSaleOrderDates                 bool      `xmlrpc:"module_sale_order_dates"`
	ModuleSalePayment                    bool      `xmlrpc:"module_sale_payment"`
	ModuleSaleTimesheet                  bool      `xmlrpc:"module_sale_timesheet"`
	ModuleStockBarcode                   bool      `xmlrpc:"module_stock_barcode"`
	ModuleStockDropshipping              bool      `xmlrpc:"module_stock_dropshipping"`
	ModuleStockLandedCosts               bool      `xmlrpc:"module_stock_landed_costs"`
	ModuleStockPickingBatch              bool      `xmlrpc:"module_stock_picking_batch"`
	ModuleVoip                           bool      `xmlrpc:"module_voip"`
	ModuleWebClearbit                    bool      `xmlrpc:"module_web_clearbit"`
	ModuleWebsiteQuote                   bool      `xmlrpc:"module_website_quote"`
	ModuleWebsiteSaleDigital             bool      `xmlrpc:"module_website_sale_digital"`
	MultiSalesPrice                      bool      `xmlrpc:"multi_sales_price"`
	MultiSalesPriceMethod                string    `xmlrpc:"multi_sales_price_method"`
	PaperformatId                        Many2One  `xmlrpc:"paperformat_id"`
	PoDoubleValidation                   string    `xmlrpc:"po_double_validation"`
	PoDoubleValidationAmount             float64   `xmlrpc:"po_double_validation_amount"`
	PoLead                               float64   `xmlrpc:"po_lead"`
	PoLock                               string    `xmlrpc:"po_lock"`
	PoOrderApproval                      bool      `xmlrpc:"po_order_approval"`
	PortalConfirmation                   bool      `xmlrpc:"portal_confirmation"`
	PortalConfirmationOptions            string    `xmlrpc:"portal_confirmation_options"`
	PropagationMinimumDelta              int64     `xmlrpc:"propagation_minimum_delta"`
	ReportFooter                         string    `xmlrpc:"report_footer"`
	ResourceCalendarId                   Many2One  `xmlrpc:"resource_calendar_id"`
	SaleNote                             string    `xmlrpc:"sale_note"`
	SalePricelistSetting                 string    `xmlrpc:"sale_pricelist_setting"`
	SaleShowTax                          string    `xmlrpc:"sale_show_tax"`
	SecurityLead                         float64   `xmlrpc:"security_lead"`
	TaxCalculationRoundingMethod         string    `xmlrpc:"tax_calculation_rounding_method"`
	TaxCashBasisJournalId                Many2One  `xmlrpc:"tax_cash_basis_journal_id"`
	TaxExigibility                       bool      `xmlrpc:"tax_exigibility"`
	UsePoLead                            bool      `xmlrpc:"use_po_lead"`
	UsePropagationMinimumDelta           bool      `xmlrpc:"use_propagation_minimum_delta"`
	UseSaleNote                          bool      `xmlrpc:"use_sale_note"`
	UseSecurityLead                      bool      `xmlrpc:"use_security_lead"`
	VatCheckVies                         bool      `xmlrpc:"vat_check_vies"`
	WriteDate                            time.Time `xmlrpc:"write_date"`
	WriteUid                             Many2One  `xmlrpc:"write_uid"`
}

type ResConfigSettingsNil struct {
	AccountHideSetupBar                  bool        `xmlrpc:"account_hide_setup_bar"`
	AliasDomain                          interface{} `xmlrpc:"alias_domain"`
	AuthSignupResetPassword              bool        `xmlrpc:"auth_signup_reset_password"`
	AuthSignupTemplateUserId             interface{} `xmlrpc:"auth_signup_template_user_id"`
	AuthSignupUninvited                  interface{} `xmlrpc:"auth_signup_uninvited"`
	AutoDoneSetting                      bool        `xmlrpc:"auto_done_setting"`
	ChartTemplateId                      interface{} `xmlrpc:"chart_template_id"`
	CodeDigits                           interface{} `xmlrpc:"code_digits"`
	CompanyCurrencyId                    interface{} `xmlrpc:"company_currency_id"`
	CompanyId                            interface{} `xmlrpc:"company_id"`
	CompanySharePartner                  bool        `xmlrpc:"company_share_partner"`
	CompanyShareProduct                  bool        `xmlrpc:"company_share_product"`
	CreateDate                           interface{} `xmlrpc:"create_date"`
	CreateUid                            interface{} `xmlrpc:"create_uid"`
	CrmAliasPrefix                       interface{} `xmlrpc:"crm_alias_prefix"`
	CurrencyExchangeJournalId            interface{} `xmlrpc:"currency_exchange_journal_id"`
	CurrencyId                           interface{} `xmlrpc:"currency_id"`
	DefaultCustomReportFooter            bool        `xmlrpc:"default_custom_report_footer"`
	DefaultDepositProductId              interface{} `xmlrpc:"default_deposit_product_id"`
	DefaultExternalEmailServer           bool        `xmlrpc:"default_external_email_server"`
	DefaultInvoicePolicy                 interface{} `xmlrpc:"default_invoice_policy"`
	DefaultPickingPolicy                 interface{} `xmlrpc:"default_picking_policy"`
	DefaultPurchaseMethod                interface{} `xmlrpc:"default_purchase_method"`
	DefaultPurchaseTaxId                 interface{} `xmlrpc:"default_purchase_tax_id"`
	DefaultSaleTaxId                     interface{} `xmlrpc:"default_sale_tax_id"`
	DefaultUserRights                    bool        `xmlrpc:"default_user_rights"`
	DisplayName                          interface{} `xmlrpc:"display_name"`
	ExternalReportLayout                 interface{} `xmlrpc:"external_report_layout"`
	FailCounter                          interface{} `xmlrpc:"fail_counter"`
	GenerateLeadFromAlias                bool        `xmlrpc:"generate_lead_from_alias"`
	GroupAnalyticAccountForPurchases     bool        `xmlrpc:"group_analytic_account_for_purchases"`
	GroupAnalyticAccounting              bool        `xmlrpc:"group_analytic_accounting"`
	GroupCashRounding                    bool        `xmlrpc:"group_cash_rounding"`
	GroupDiscountPerSoLine               bool        `xmlrpc:"group_discount_per_so_line"`
	GroupDisplayIncoterm                 bool        `xmlrpc:"group_display_incoterm"`
	GroupManageVendorPrice               bool        `xmlrpc:"group_manage_vendor_price"`
	GroupMassMailingCampaign             bool        `xmlrpc:"group_mass_mailing_campaign"`
	GroupMultiCompany                    bool        `xmlrpc:"group_multi_company"`
	GroupMultiCurrency                   bool        `xmlrpc:"group_multi_currency"`
	GroupPricelistItem                   bool        `xmlrpc:"group_pricelist_item"`
	GroupProductPricelist                bool        `xmlrpc:"group_product_pricelist"`
	GroupProductVariant                  bool        `xmlrpc:"group_product_variant"`
	GroupProformaSales                   bool        `xmlrpc:"group_proforma_sales"`
	GroupRouteSoLines                    bool        `xmlrpc:"group_route_so_lines"`
	GroupSaleDeliveryAddress             bool        `xmlrpc:"group_sale_delivery_address"`
	GroupSaleLayout                      bool        `xmlrpc:"group_sale_layout"`
	GroupSalePricelist                   bool        `xmlrpc:"group_sale_pricelist"`
	GroupShowPriceSubtotal               bool        `xmlrpc:"group_show_price_subtotal"`
	GroupShowPriceTotal                  bool        `xmlrpc:"group_show_price_total"`
	GroupStockAdvLocation                bool        `xmlrpc:"group_stock_adv_location"`
	GroupStockMultiLocations             bool        `xmlrpc:"group_stock_multi_locations"`
	GroupStockMultiWarehouses            bool        `xmlrpc:"group_stock_multi_warehouses"`
	GroupStockPackaging                  bool        `xmlrpc:"group_stock_packaging"`
	GroupStockProductionLot              bool        `xmlrpc:"group_stock_production_lot"`
	GroupStockTrackingLot                bool        `xmlrpc:"group_stock_tracking_lot"`
	GroupStockTrackingOwner              bool        `xmlrpc:"group_stock_tracking_owner"`
	GroupSubtaskProject                  bool        `xmlrpc:"group_subtask_project"`
	GroupUom                             bool        `xmlrpc:"group_uom"`
	GroupUseLead                         bool        `xmlrpc:"group_use_lead"`
	GroupWarningAccount                  bool        `xmlrpc:"group_warning_account"`
	GroupWarningPurchase                 bool        `xmlrpc:"group_warning_purchase"`
	GroupWarningSale                     bool        `xmlrpc:"group_warning_sale"`
	GroupWarningStock                    bool        `xmlrpc:"group_warning_stock"`
	HasAccountingEntries                 bool        `xmlrpc:"has_accounting_entries"`
	HasChartOfAccounts                   bool        `xmlrpc:"has_chart_of_accounts"`
	Id                                   interface{} `xmlrpc:"id"`
	IsInstalledSale                      bool        `xmlrpc:"is_installed_sale"`
	LastUpdate                           interface{} `xmlrpc:"__last_update"`
	LeaveTimesheetProjectId              interface{} `xmlrpc:"leave_timesheet_project_id"`
	LeaveTimesheetTaskId                 interface{} `xmlrpc:"leave_timesheet_task_id"`
	LockConfirmedPo                      bool        `xmlrpc:"lock_confirmed_po"`
	ModuleAccount3wayMatch               bool        `xmlrpc:"module_account_3way_match"`
	ModuleAccountAccountant              bool        `xmlrpc:"module_account_accountant"`
	ModuleAccountAsset                   bool        `xmlrpc:"module_account_asset"`
	ModuleAccountBankStatementImportCamt bool        `xmlrpc:"module_account_bank_statement_import_camt"`
	ModuleAccountBankStatementImportCsv  bool        `xmlrpc:"module_account_bank_statement_import_csv"`
	ModuleAccountBankStatementImportOfx  bool        `xmlrpc:"module_account_bank_statement_import_ofx"`
	ModuleAccountBankStatementImportQif  bool        `xmlrpc:"module_account_bank_statement_import_qif"`
	ModuleAccountBatchDeposit            bool        `xmlrpc:"module_account_batch_deposit"`
	ModuleAccountBudget                  bool        `xmlrpc:"module_account_budget"`
	ModuleAccountDeferredRevenue         bool        `xmlrpc:"module_account_deferred_revenue"`
	ModuleAccountPayment                 bool        `xmlrpc:"module_account_payment"`
	ModuleAccountPlaid                   bool        `xmlrpc:"module_account_plaid"`
	ModuleAccountReports                 bool        `xmlrpc:"module_account_reports"`
	ModuleAccountReportsFollowup         bool        `xmlrpc:"module_account_reports_followup"`
	ModuleAccountSepa                    bool        `xmlrpc:"module_account_sepa"`
	ModuleAccountSepaDirectDebit         bool        `xmlrpc:"module_account_sepa_direct_debit"`
	ModuleAccountTaxcloud                bool        `xmlrpc:"module_account_taxcloud"`
	ModuleAccountYodlee                  bool        `xmlrpc:"module_account_yodlee"`
	ModuleAuthLdap                       bool        `xmlrpc:"module_auth_ldap"`
	ModuleAuthOauth                      bool        `xmlrpc:"module_auth_oauth"`
	ModuleBaseGengo                      bool        `xmlrpc:"module_base_gengo"`
	ModuleBaseImport                     bool        `xmlrpc:"module_base_import"`
	ModuleCrmPhoneValidation             bool        `xmlrpc:"module_crm_phone_validation"`
	ModuleCurrencyRateLive               bool        `xmlrpc:"module_currency_rate_live"`
	ModuleDelivery                       bool        `xmlrpc:"module_delivery"`
	ModuleDeliveryBpost                  bool        `xmlrpc:"module_delivery_bpost"`
	ModuleDeliveryDhl                    bool        `xmlrpc:"module_delivery_dhl"`
	ModuleDeliveryFedex                  bool        `xmlrpc:"module_delivery_fedex"`
	ModuleDeliveryUps                    bool        `xmlrpc:"module_delivery_ups"`
	ModuleDeliveryUsps                   bool        `xmlrpc:"module_delivery_usps"`
	ModuleGoogleCalendar                 bool        `xmlrpc:"module_google_calendar"`
	ModuleGoogleDrive                    bool        `xmlrpc:"module_google_drive"`
	ModuleGoogleSpreadsheet              bool        `xmlrpc:"module_google_spreadsheet"`
	ModuleHrOrgChart                     bool        `xmlrpc:"module_hr_org_chart"`
	ModuleHrTimesheet                    bool        `xmlrpc:"module_hr_timesheet"`
	ModuleInterCompanyRules              bool        `xmlrpc:"module_inter_company_rules"`
	ModuleL10nEuService                  bool        `xmlrpc:"module_l10n_eu_service"`
	ModuleL10nUsCheckPrinting            bool        `xmlrpc:"module_l10n_us_check_printing"`
	ModulePad                            bool        `xmlrpc:"module_pad"`
	ModulePrintDocsaway                  bool        `xmlrpc:"module_print_docsaway"`
	ModuleProcurementJit                 interface{} `xmlrpc:"module_procurement_jit"`
	ModuleProductEmailTemplate           bool        `xmlrpc:"module_product_email_template"`
	ModuleProductExpiry                  bool        `xmlrpc:"module_product_expiry"`
	ModuleProductMargin                  bool        `xmlrpc:"module_product_margin"`
	ModuleProjectForecast                bool        `xmlrpc:"module_project_forecast"`
	ModuleProjectTimesheetHolidays       bool        `xmlrpc:"module_project_timesheet_holidays"`
	ModuleProjectTimesheetSynchro        bool        `xmlrpc:"module_project_timesheet_synchro"`
	ModulePurchaseRequisition            bool        `xmlrpc:"module_purchase_requisition"`
	ModuleRatingProject                  bool        `xmlrpc:"module_rating_project"`
	ModuleSaleCoupon                     bool        `xmlrpc:"module_sale_coupon"`
	ModuleSaleMargin                     bool        `xmlrpc:"module_sale_margin"`
	ModuleSaleOrderDates                 bool        `xmlrpc:"module_sale_order_dates"`
	ModuleSalePayment                    bool        `xmlrpc:"module_sale_payment"`
	ModuleSaleTimesheet                  bool        `xmlrpc:"module_sale_timesheet"`
	ModuleStockBarcode                   bool        `xmlrpc:"module_stock_barcode"`
	ModuleStockDropshipping              bool        `xmlrpc:"module_stock_dropshipping"`
	ModuleStockLandedCosts               bool        `xmlrpc:"module_stock_landed_costs"`
	ModuleStockPickingBatch              bool        `xmlrpc:"module_stock_picking_batch"`
	ModuleVoip                           bool        `xmlrpc:"module_voip"`
	ModuleWebClearbit                    bool        `xmlrpc:"module_web_clearbit"`
	ModuleWebsiteQuote                   bool        `xmlrpc:"module_website_quote"`
	ModuleWebsiteSaleDigital             bool        `xmlrpc:"module_website_sale_digital"`
	MultiSalesPrice                      bool        `xmlrpc:"multi_sales_price"`
	MultiSalesPriceMethod                interface{} `xmlrpc:"multi_sales_price_method"`
	PaperformatId                        interface{} `xmlrpc:"paperformat_id"`
	PoDoubleValidation                   interface{} `xmlrpc:"po_double_validation"`
	PoDoubleValidationAmount             interface{} `xmlrpc:"po_double_validation_amount"`
	PoLead                               interface{} `xmlrpc:"po_lead"`
	PoLock                               interface{} `xmlrpc:"po_lock"`
	PoOrderApproval                      bool        `xmlrpc:"po_order_approval"`
	PortalConfirmation                   bool        `xmlrpc:"portal_confirmation"`
	PortalConfirmationOptions            interface{} `xmlrpc:"portal_confirmation_options"`
	PropagationMinimumDelta              interface{} `xmlrpc:"propagation_minimum_delta"`
	ReportFooter                         interface{} `xmlrpc:"report_footer"`
	ResourceCalendarId                   interface{} `xmlrpc:"resource_calendar_id"`
	SaleNote                             interface{} `xmlrpc:"sale_note"`
	SalePricelistSetting                 interface{} `xmlrpc:"sale_pricelist_setting"`
	SaleShowTax                          interface{} `xmlrpc:"sale_show_tax"`
	SecurityLead                         interface{} `xmlrpc:"security_lead"`
	TaxCalculationRoundingMethod         interface{} `xmlrpc:"tax_calculation_rounding_method"`
	TaxCashBasisJournalId                interface{} `xmlrpc:"tax_cash_basis_journal_id"`
	TaxExigibility                       bool        `xmlrpc:"tax_exigibility"`
	UsePoLead                            bool        `xmlrpc:"use_po_lead"`
	UsePropagationMinimumDelta           bool        `xmlrpc:"use_propagation_minimum_delta"`
	UseSaleNote                          bool        `xmlrpc:"use_sale_note"`
	UseSecurityLead                      bool        `xmlrpc:"use_security_lead"`
	VatCheckVies                         bool        `xmlrpc:"vat_check_vies"`
	WriteDate                            interface{} `xmlrpc:"write_date"`
	WriteUid                             interface{} `xmlrpc:"write_uid"`
}

var ResConfigSettingsModel string = "res.config.settings"

type ResConfigSettingss []ResConfigSettings

type ResConfigSettingssNil []ResConfigSettingsNil

func (s *ResConfigSettings) NilableType_() interface{} {
	return &ResConfigSettingsNil{}
}

func (ns *ResConfigSettingsNil) Type_() interface{} {
	s := &ResConfigSettings{}
	return load(ns, s)
}

func (s *ResConfigSettingss) NilableType_() interface{} {
	return &ResConfigSettingssNil{}
}

func (ns *ResConfigSettingssNil) Type_() interface{} {
	s := &ResConfigSettingss{}
	for _, nsi := range *ns {
		*s = append(*s, *nsi.Type_().(*ResConfigSettings))
	}
	return s
}
